// react hooks
import { useState } from 'react';

// API functions
import { getRandomQuote } from './api/quotes.js';

// nextjs copmonents/stylesheets
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// MUI components
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';


export default function Home() {

  const [quoteData, setQuoteData] = useState({
    quote: "Quote text here",
    author: "Author name here"
  })

  const handleClick = () => {
    /* OK, so we were having some issues with fetching from the zenquotes API.
       I'll take you through a step-by-step process of how I found out what was wrong.

       Like I mentioned in some of your Assignment 1 feedback, separating API & UI layers
       makes code more readable & debugging less of a confusing headache, so let's start there.
    
       First, we'll just make an API call and look in the console.
    */
    getRandomQuote()
  }

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={handleClick}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}