import { useEffect, useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export default function Home() {

  const QUOTE_API_URL = 'https://dummyjson.com/quotes/'

  const [quoteData, setQuoteData] = useState({
    quote: "Quote here.",
    author: "Author here"
  })

  const getRandomQuote = () => {
    fetch(`${QUOTE_API_URL}/random`)
      .then((response)=> {
        return response.json()
      }).then((data)=> {
        console.log(data)
        setQuoteData({
          quote: data.quote,
          author: data.author
        })
      })  
  }

  useEffect(

    // param 1: the callback (logic that should fire for the effect)
    () => {
      getRandomQuote()
    },

    // param 2: dependency array (empty — fire only when component mounts)
    []
  )

  /* If you look in your console, you'll notice this fires twice!
     
     That's because we're using React strict mode (see next.config.js), which is a debug/dev mode.
       more here if you're interested: https://react.dev/reference/react/StrictMode

     e.g. effects re-fire to ensure that any cleanup (if present) happens properly, etc.
     Just mentioning this here so you don't go nuts during examples/assignments wondering why stuff
     is happening twice.

     If you want proof, set reactStrictMode to false in next.config.js and you'll see the effect
     fire only once.

  */

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={getRandomQuote}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}
