// react hooks
import { useState } from 'react';

// data
import { MOVIE_LIST } from '../utils/movies'

// MUI components
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Alert from '@mui/material/Alert';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';


export default function Home() {

  {/* [statefulValue, setStatefulValue] = useState(defaultValue) */}
  const [searchText, setSearchText] = useState("")
  const [year, setYear] = useState("")

  // this is just what we're displaying from
  const [movies, setMovies] = useState(MOVIE_LIST)

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(`search: ${searchText}`)
    console.log(`year: ${year}`)
    filterMovies();
  }

  const filterMovies = () => {
    /* Remember: React stateful variables are *immutable*, so I always need to
                completely reconstruct the value I want to write to pass to the setter.

                I can't e.g. push or pop from the 'movies' variable; it's immutable.
    */

    // 1. set up a new copy of the movies array
    let filteredMovies = [...MOVIE_LIST]

    // 2. if there's a search term, filter the copy array for that term
    if (searchText.trim()) {
      // I'm going to use [].filter() to reconstruct my array.
      // -> With [].filter(), only elements that pass the condition are included in the new array.
      // -> newArray = oldArray.filter((element) => {some condition})
      filteredMovies = filteredMovies.filter(
        (movie) => {
          // in [].filter(), you're returning *whether* something is true/truthy or false/falsey,
          // *not* specific values themselves.
          return movie.name.toLowerCase().includes(
            searchText.trim().toLowerCase()
          )
        }
      )
    }

    // 3. if there's a year, ditto
    if (year.trim()) {
      // I'm going to use [].filter() to reconstruct my array.
      // -> With [].filter(), only elements that pass the condition are included in the new array.
      // -> newArray = oldArray.filter((element) => {some condition})
      filteredMovies = filteredMovies.filter(
        (movie) => {
          return movie.year === parseInt(year.trim())
        }
      )
    }

    // 4. now that I've filtered my mutable, copied array based on inputs, I can
    //    pass that to the setter for the stateful movies variable.
    setMovies(filteredMovies)
  } 


  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography variant="h2" component="h2" style={{textAlign: "center"}}>
            Movies
          </Typography>
          <form
            style={{width: '100%'}}
            onSubmit={handleSubmit}
          >
            <Grid container spacing={2}>
              {/* This uses an older version of MUI, specific to this package-lock.json,
                  hence the use of item & xs props.
              */}
              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(e) => setSearchText(e.target.value)}
                  value={searchText}
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(e) => setYear(e.target.value)}
                  value={year}
                 
                />
              </Grid>
              <Grid item xs={2}>
                <Button
                  type="submit"
                  variant="contained"
                >Filter</Button>
              </Grid>
              <Grid item xs={10}>
                {/* Add the error message here*/}
              </Grid>
            </Grid>
          </form>
          <List sx={{width: `100%`}}>
          { movies.map((movieData, index)=> {
              return <ListItem key={index}>
                <ListItemText>
                  <Typography variant="p" component="div">
                    {movieData.name} ({movieData.year})
                  </Typography>
                </ListItemText>
              </ListItem>
            })
          }
          </List>
        </Container>
      </main>
    </div>
  )
}
